### ISSUE TITLE
Cannot preview any choice element row from a Data Set

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper-NHSD/mdm-plugin-nhs-data-dictionary#70]
# Overview

The data set "Clinical Data Sets > COSDS > Cancer Outcomes and Services Data Set - Core" has a table called "DEMOGRAPHICS - CORE". The live published website looks like this:

![image](https://github.com/user-attachments/assets/404de6d9-23d1-40c1-a1dc-3629219c4064)

But the Orchestrator preview does not show the address choice field:

![image](https://github.com/user-attachments/assets/5197208e-ecec-4e86-80fe-18d4efd95e2f)

# Mauro Views

In Mauro, the address choice field is set up like this:

![image](https://github.com/user-attachments/assets/aeb9c783-9a4c-4af6-b544-53da0658c502)

This is the "Data Set Table" profile for the "Address Choice" class:

![image](https://github.com/user-attachments/assets/f42abb94-793d-494a-b147-9751ec900b80)

And here is some additional hidden metadata to complete the row information:

![image](https://github.com/user-attachments/assets/85929b0d-5a23-4ab1-8654-a0e9b2c2922f)

# Other choice types

Upon further investigation, I don't think any choice type is being rendered to the HTML preview of a data set table. For example, this is the live published "Diagnostic Imaging Data Set" from https://www.datadictionary.nhs.uk/data_sets/clinical_data_sets/diagnostic_imaging_data_set.html:

![image](https://github.com/user-attachments/assets/d9472b26-c41d-43de-9074-f692f960a651)

This is the Mauro structure of the "IMAGING CODE" choice:

![image](https://github.com/user-attachments/assets/69c1782d-6c91-4878-924c-48284d761ace)

But this is the preview of the data set in the Orchestrator. Notice the choice between "IMAGING CODE" elements is missing:

![image](https://github.com/user-attachments/assets/391d4343-017a-4c27-9d38-b96bf6160643)

# Fixes

- [x] The "Address Choice" profile field in "Data Set Table" profile should be a boolean type, not a string
- [x] Update the preview to use the address choice information provided to display the same output as the live data dictionary site

**Comment by mhocc** [comment]
This is partially working: it gets the address links and produces the two options but there's too much hard-coding and the links are to https://datadictionary.nhs.uk/ and not styled correctly
