### ISSUE TITLE
Preview of Data Set tables can include HTML paragraph tags

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper-NHSD/mdm-plugin-nhs-data-dictionary#82]
# Overview

Preview (and possibly DITA generation) of data set table headers will output raw HTML tags such as `<p>` when it should not.

# Steps to replicate

1. On the Test system, view in the Mauro the branch "Test branch" under "Data Dictionary > Active Branches > Angie"
2. View "Data Sets > Clinical Data Sets > National Eye Colour Data Set > REFERRALS"
3. Notice the description is standard HTML
4. Preview this data set in the Orchestrator
5. The output looks like this:

![image](https://github.com/user-attachments/assets/638c2093-63e9-4028-b151-ee13e5534add)

# Expected behaviour

The table description should render HTML content correctly.

# Related

- NHSDigital/DataDictionaryPublication#505

# The problem

Reviewing some of the behaviour I found the following:

1.  The `<p>` tags can be seen if the Markdown tab is selected
2.  If the `<p>` tags are removed and the text written as two lines with a blank line between them then the preview in the editor renders correctly but in the orchestrator the paragraphs are joined
3.  When two lines are added in the HTML tab they are written to the backend as: `<p>line1<br><br>line2<br></p>` which is a wrong interpretation and then that text is show literally in the orchestration UI so I suspect the orchestration UI element is treating all content as plain text with no rendering soe either it should be updated or it should strip all tags.
4.  When re-editing the text and selecting Markdown the tags can be seen but I would expect the HTML tags to have been converted to markdown.
5.  Removing the HTML tags in the Markdown view and selecting Preview shows the expected layout and when saved the lines are separated by newlines so there's an inconsistency between the Markdown and HTML editors.  In addition the description shown in the MDM UI after editing as Markdown no longer shows two lines explaining the problem seen in ii. above.
6.  The link to the markdown guide in the editor navigates to the markdown guide for GitHub which is clearly not what is happening here
7.  When switching between Markdown and HTML tabs the text gets further messed-up; if markdown is entered as:
     
 ```
     # Heading

     para1

     para2
```
Switching to HTML shows:
```
    # A heading para1 para2
```
Switching back to Markdown:
```
     <p># Heading

     para1

     para2</p>
```

Which is just a mess.

Clearly it works in some situations but not all.  I think the bottom line is that the editor is broken and the storage of the text needs some thinking about—it at least needs to be consistent—either markdown or html.

**Comment by mhocc** [comment]
In the first instance, the markdown tab needs could be disabled to avoid mixing markdown & html an only allow the front-end to submit html for storage.  Based on the description above, any UI components which do not process the response as html should be updated to do so.
